var TextsEN = {
  towersBeatHighScore: 'Blow up more than {0} <img src="img/pause/bomb.png"/> !',
  highscoreText: 'Highscore : {0} bomb{1}',
  score: '<span class="bomb"></span>{0} ',
  newHighscoreReached: 'New highscore!',
  storyTutorialCompleted: 'Well done.<br/> Now get ready...',
  level: 'Level {0}...',
  questsTitle: 'Bonus challenge!',
  questsSpeech: 'To get extra<br/> stars, blow up <br/>all bricks except one...',
  questsObjectives: 'Try to leave one of these...',
  questsObjective: 'Try to leave a...',
  towerIntro: 'Blow up as many bombs as you can! And remember... <br/>10 is a <img src="img/pause/bomb.png"/> !',
  questsItemIntroText: 'Tap the star above<br/> for a bonus challenge !',
  or: 'or',
  firstStar: 'You\'ve earned a <img src="img/quests/star.png" /> !',
  secondStar: 'Great! And another <img src="img/quests/star.png" /> !',
  langNL: 'Nederlands',
  langEN: 'English',
  credits: [
	  'Numolition',
	  'a game by Q42',
	  '||',
	  'Game design',
	  'Martin Kool',
	  '',
	  'Art Direction',
	  'Richard Lems',
	  '',
		'Coding',
		'Martin Kool',
		'Benjamin de Jager',
		'Kars Veling',
		'',
		'Level design',
		'Zias Kool',
		'Martin Kool',
		'',
		'Music',
		'Serge Essiambre',
		'',
		'Roadie',
		'Rahul Choudhury',
		'',
		'Fanboy',
		'Bram Stege',
		'',
		'Stunts',
		'Marcel Duin',
		'',
		'Quality Crew',
		'Zias',
		'Nanou',
		'Yala',
		'Isa',
		'Evi',
		'Lucas',
		'Ewout',
		'Laure\'',
		'Aniek',		
		'',
		'(c) 2013 by Q42',
		'www.q42.com',
		'www.numolition.com'
  	].join('|'),
  quentoTry: 'Try our other game... Quento!',
  quentoPlayers: 'Over 250.000 players (and) counting...'
};

var TextsNL = {
  towersBeatHighScore: 'Can you place more than {0} bomb{1}?',
  highscoreText: 'Highscore : {0} bomb{1}',
  level: 'Level {0}...',
  questsSpeech: 'Can you clear<br/> the level and end up with only ONE brick remaining?',
  questsObjectives: 'Try to leave one of these...',
  questsObjective: 'Try to leave a...',
  towerIntro: 'Make a 10 to build bombs <br/> like 7 + 3 = <img src="img/pause/bomb.png" /><br/> Then blow them up !',
  questsItemIntroText: 'Tap the star above<br/> for a bonus challenge !',
  or: 'or',
  langNL: 'Nederlands',
  langEN: 'English',
  credits: 'Numolition|by Q42||Game design|Martin Kool||Art Direction|Richard Lems||' +
  				 'Coding|Martin Kool|Benjamin de Jager|Kars Veling||Level design|Martin Kool|Zias Kool||Music|Serge Essiambre',
  quentoTry: 'Speel ook eens... Quento!',
  quentoPlayers: 'Al meer dan 250,000 spelers...'
};

var Texts = TextsEN;